name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compile Java
        shell: cmd
        run: |
          mkdir out
          for /R src %%f in (*.java) do javac -d out %%f

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=Task-3
            -Dsonar.projectName=Task-3
            -Dsonar.sources=.
            -Dsonar.java.binaries=out
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
